ExerciseEveryDay/urls.py
from django.contrib import admin
from django.urls import path
from app01 import views

urlpatterns = [
    # 转入登录界面
    path('login/', views.login, name='login'),
    path('index/home/', views.index_home, name='index_home'),
    path('index/home_fwc/', views.index_home_fwc, name='index_home_fwc'),
    path('index/ranking/', views.index_ranking, name='index_ranking'),
    path('game/', views.game),
    path('signup/', views.signup, name='signup'),
    path('image/code/', views.image_code),
    path('logout/', views.logout),
    path('video/',views.video),
    path('fwc_video/',views.fwc_video),
    path('update-score/',views.update_score),
    path('update-fwc-score/',views.update_fwc_score),
    path('fwc/', views.fwc_view),
    path('get_counter_data/', views.get_counter_data, name='get_counter_data'),
   # path('index/ranking/', views.top_three_scores, name='top_three_scores')
]

app01/models.py
from django.db import models


# Create your models here.
class UserInfo(models.Model):
    """用户信息"""
    username = models.CharField(verbose_name="用户名", max_length=32)
    password = models.CharField(verbose_name="密码", max_length=64)
    max_score = models.IntegerField(default=0)
    fwc_score = models.IntegerField(default=0)

app01/views.py
import mediapipe as mp
import numpy as np
from django.shortcuts import render, redirect
import cv2
from django.http import StreamingHttpResponse, JsonResponse
from django.views.decorators.clickjacking import xframe_options_exempt

from django.shortcuts import render, redirect, HttpResponse
from django import forms
import pymysql
from . import models
from utils.code import check_code
from django.shortcuts import HttpResponse
from io import BytesIO
from app01.models import UserInfo
from collections import deque

q_left = deque(maxlen=10)
left_flag = 0
q_right = deque(maxlen=10)
right_flag = 0
user = {'username': ""}


def image_code(request):
    """ 生成图片验证码 """
    # 调用pillow函数,生成图片
    img, code_string = check_code()

    # 写入到自己的session中,以便于后续获取验证码再进行校验
    request.session['image_code'] = code_string
    # 给session设置 60s 超时
    request.session.set_expiry(60)

    # 将图片保存到内存
    stream = BytesIO()
    img.save(stream, 'png')
    return HttpResponse(stream.getvalue())


# 用户登录表单
class LoginForm(forms.Form):
    username = forms.CharField(
        # label="用户名",
        widget=forms.TextInput(attrs={"class": "form-control", "placeholder": "请输入用户名"}),
        required=True,
    )
    password = forms.CharField(
        # label="密码",
        # render_value=True 表示当提交后,如果密码输入错误,不会自动清空密码输入框的内容
        widget=forms.PasswordInput(attrs={"class": "form-control", "placeholder": "请输入密码"}, ),
        required=True,
    )
    code = forms.CharField(
        # label="验证码",
        widget=forms.TextInput(attrs={"class": "form-control", "placeholder": "请输入验证码"}),
        required=True,
    )

    # def clean_password(self):
    #     pwd = self.cleaned_data.get("password")
    #     return md5(pwd)


# 用户注册表单
class SignupForm(forms.Form):
    username = forms.CharField(
        label="用户名",
        widget=forms.TextInput(attrs={"class": "form-control", "placeholder": "请输入用户名"}),
        required=True,
    )
    password = forms.CharField(
        label="密码",
        # render_value=True 表示当提交后,如果密码输入错误,不会自动清空密码输入框的内容
        widget=forms.PasswordInput(attrs={"class": "form-control", "placeholder": "请输入密码"}, ),
        required=True,
    )
    confirmed_password = forms.CharField(
        label="确认密码",
        widget=forms.PasswordInput(attrs={"class": "form-control", "placeholder": "确认密码"}, ),
        required=True,
    )
    # def clean_password(self):
    #     pwd = self.cleaned_data.get("password")
    #     return md5(pwd)


def login(request):
    """登录"""
    if request.method == "GET":
        form = LoginForm()
        return render(request, 'login.html', {"form": form})

    if 'btn2' in request.POST:
        return redirect('/signup/')

    form = LoginForm(data=request.POST)

    if form.is_valid():
        # 验证成功, 获取到的用户名和密码

        # 拿到用户名，便于后续显示
        global user
        user = {'username': form.cleaned_data['username']}
        # 验证码的校验
        user_input_code = form.cleaned_data.pop('code')
        image_code = request.session.get('image_code', "")
        if image_code.upper() != user_input_code.upper():
            form.add_error("code", "验证码错误")
            return render(request, 'login.html', {"form": form})

        # 去数据库校验用户名和密码是否正确
        User_object = models.UserInfo.objects.filter(**form.cleaned_data).first()
        # 如果数据库中没有查询到数据
        if not User_object:
            # 手动抛出错误显示在"password"字段下
            form.add_error("username", "用户名或密码错误")
            return render(request, 'login.html', {"form": form})

        # 如果用户名密码正确
        # 网站生成随机字符创,写到用户浏览器的cookie中,再写入到服务器的session中
        request.session["info"] = {'username': User_object.username}
        # 重新设置session的超时时间,因为之前设置的session的超时时间的 60s
        request.session.set_expiry(60 * 60 * 24)
        return redirect("/index/home")
    return redirect('/login')


def index_home(request):
    if request.method == 'GET':
        # 处理 GET 请求的逻辑
        return render(request, "home.html", {'user': user})


def index_home_fwc(request):
    if request.method == 'GET':
        # 处理 GET 请求的逻辑
        return render(request, "home_fwc.html", {'user': user})


def index_ranking(request):
    print("aa")
    top_three_users = UserInfo.objects.order_by('-max_score')[:3]
    # top_three_users = [
    #     {'username': 'user1', 'max_score': 100},
    #     {'username': 'user2', 'max_score': 90},
    #     {'username': 'user3', 'max_score': 80},
    # ]
    top_three_fwcers = UserInfo.objects.order_by('-fwc_score')[:3]
    print(top_three_users)
    return render(request, 'ranking.html',
                  {'top_three_users': top_three_users, 'user': user, 'fwcer': top_three_fwcers})


def signup(request):
    """注册"""
    if request.method == "GET":
        form = SignupForm()
        return render(request, 'signup.html', {"form": form})

    form = SignupForm(data=request.POST)
    if form.is_valid():
        # 检查用户名是否已经注册过
        existing_user = models.UserInfo.objects.filter(username=form.cleaned_data['username']).exists()
        if existing_user:
            form.add_error("username", "该用户名已经被注册")
            return render(request, 'signup.html', {"form": form})

        # 检查确认密码是否和密码输入一致
        if form.cleaned_data['password'] == form.cleaned_data['confirmed_password']:
            user_info = UserInfo(username=form.cleaned_data['username'], password=form.cleaned_data['password'])
            user_info.save()
            return redirect('/login/')
        form.add_error("confirmed_password", "密码不一致")
        return render(request, 'signup.html', {"form": form})
    return redirect('/signup/')


def game(request):
    global left_flag
    global right_flag

    if (left_flag == 1) and request.method == "POST":
        print("发送左")
        left_flag = 0
        return JsonResponse({"list": list(q_left)})
    if (right_flag == 1) and request.method == "POST":
        print("发送右")
        right_flag = 0
        return JsonResponse({"list": list(q_right)})

    if request.method == "GET":
        return render(request, "game.html", {'user': user})
    return HttpResponse()


def fwc_view(request):
    global fwc_counter
    fwc_counter = 0
    return render(request, 'fwc.html')


def logout(request):
    """ 退出登录 """

    # 清楚当前session
    request.session.clear()

    return redirect("/login/")


def calculate_angle(a, b, c):
    a = np.array(a)  # First
    b = np.array(b)  # Mid
    c = np.array(c)  # End

    radians = np.arctan2(c[1] - b[1], c[0] - b[0]) - np.arctan2(a[1] - b[1], a[0] - b[0])
    angle = np.abs(radians * 180.0 / np.pi)

    if angle > 180.0:
        angle = 360 - angle

    return angle


fwc_counter = 0


def get_counter_data(request):
    global fwc_counter
    return JsonResponse({'counter': fwc_counter})


def gen_display(camera):
    global left_flag
    global right_flag
    mp_draw = mp.solutions.drawing_utils
    mp_hands = mp.solutions.hands
    hands = mp_hands.Hands(max_num_hands=2)

    # 循环读取摄像头的画面
    while True:
        # 读取一帧图片
        ret, frame = camera.read()
        frame = cv2.flip(frame, 1)

        if ret:
            # 将图片进行编码
            frameRGB = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)

            # 手部检测
            hands_results = hands.process(frameRGB)
            if hands_results.multi_hand_landmarks:
                for hand_landmarks in hands_results.multi_hand_landmarks:
                    handedness = hands_results.multi_handedness[0]
                    # mp_draw.draw_landmarks(frame, hand_landmarks, mp_hands.HAND_CONNECTIONS)
                    if handedness.classification[0].label == 'Left':
                        q_left.append({"left_x": hand_landmarks.landmark[8].x * 650,
                                       "left_y": hand_landmarks.landmark[8].y * 500})
                        left_flag = 1
                    else:
                        q_right.append({"right_x": hand_landmarks.landmark[8].x * 650,
                                        "right_y": hand_landmarks.landmark[8].y * 500})
                        right_flag = 1

            # 编码并传输视频流
            ret, frame = cv2.imencode('.jpeg', frame)
            if ret:
                # 转换为字节类型，并存储在迭代器中
                yield (b'--frame\r\n'
                       b'Content-Type: image/jpeg\r\n\r\n' + frame.tobytes() + b'\r\n')


def fwc_display(camera):
    mp_draw = mp.solutions.drawing_utils
    mp_pose = mp.solutions.pose
    pose = mp_pose.Pose(min_detection_confidence=0.5, min_tracking_confidence=0.5)
    global fwc_counter
    stage = None
    max_angle = 160
    min_angle = 60

    # 循环读取摄像头的画面
    while True:
        # 读取一帧图片
        ret, frame = camera.read()
        frame = cv2.flip(frame, 1)

        if ret:
            # 将图片进行编码
            frameRGB = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)

            # 俯卧撑检测
            pose_results = pose.process(frameRGB)
            if pose_results.pose_landmarks:
                landmarks = pose_results.pose_landmarks.landmark
                # 获得坐标
                shoulder = [landmarks[mp_pose.PoseLandmark.LEFT_SHOULDER.value].x,
                            landmarks[mp_pose.PoseLandmark.LEFT_SHOULDER.value].y]
                elbow = [landmarks[mp_pose.PoseLandmark.LEFT_ELBOW.value].x,
                         landmarks[mp_pose.PoseLandmark.LEFT_ELBOW.value].y]
                wrist = [landmarks[mp_pose.PoseLandmark.LEFT_WRIST.value].x,
                         landmarks[mp_pose.PoseLandmark.LEFT_WRIST.value].y]
                angle = calculate_angle(shoulder, elbow, wrist)

                # 俯卧撑计数器
                if angle > max_angle and stage != 'down':
                    stage = "up"
                if angle > max_angle and stage == 'down':
                    stage = "up"
                    fwc_counter += 1
                    print(fwc_counter)
                if angle < min_angle and stage == 'up':
                    stage = "down"

                    # 绘制出关键点的连接线
            # mp_draw.draw_landmarks(frame, pose_results.pose_landmarks, mp_pose.POSE_CONNECTIONS,

app01/templates/frame.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block page-css %}

    {% endblock %}
</head>
<body>
<div class="all_part">
    <div class="left">
{#        此处应该是用户头像#}
        <img src="{% static 'image/introduction_photo.jpg' %}">
        <div>用户名</div>
    </div>
    <div class="right">
        <div class="content">
            {% block content %}

            {% endblock %}
        </div>
    </div>

</div>


<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
{% block page-js %}

{% endblock %}
</body>
</html>

app01/templates/fwc.html
{% extends 'index.html' %}
{% load static %}

{% block page-css %}
    <title>俯卧撑计数器</title>
    <style>
        body {
            margin: 0;
            padding: 0;
            height: 100vh;
            display: flex;
            justify-content: center;
            align-items: center;
            background-image: url("{% static 'image/bg_fwc01.png' %}");
            background-size: cover;
            font-family: Arial, sans-serif;
        }

        .time {
            color: rgb(56, 87, 254);
            font-size: 34px;
            font-weight: bolder;
        }

        #video-feed {
            max-width: 640px;
            height: 505px;
            border: 3px solid #fff;
            border-radius: 8px;
            margin: auto;
        }

        .content {
            position: relative;
            width: 850px;
            height: 600px;
            margin-top: 110px;
            margin-left: 290px;
            border-radius: 15px;
            background-color: rgba(255, 255, 255, 0.75);
            background-size: cover;
            display: flex;
            justify-content: space-between;
            padding: 20px;
        }

        .time-box {
            display: inline-block;
            margin-top: 50px;
            margin-left: 10px;
            height: 150px;
            width: 150px;
            background-color: transparent;
        }

        .time {
            margin-top: 30px;
            margin-left: 37px;
        }

        #counter {
            font-size: 40px;
            color: #fff;
        }

        #start-btn {
            margin-top: 12px;
            margin-left: 45px;
            padding: 10px 20px;
            font-size: 16px;
            background-color: rgb(56, 87, 254);
            color: #fff;
            border: 1px solid transparent;
            border-radius: 5px;
            transition: background-color 0.3s, border-color 0.3s, color 0.3s;
        }

        #start-btn:hover {
            background-color: #fff;
            color: rgb(56, 87, 254);
            border: 1px solid rgb(56, 87, 254);
        }
    </style>
{% endblock %}

{% block content %}
    <div class="content">
        <div style="display:inline-block;float:left;width:645px;height:510px;">
            <iframe id="video-feed" width="640" height="505"></iframe>
        </div>
        <div>
            <div class="time-box">
                <div class="time">得分</div>
                <div class="time" id="counter">0</div>
            </div>
            <div class="time-box">
                <div class="time">时间</div>
                <span class="time" id="timer">180</span><span class="time">s</span>
                <button type="submit" id="start-btn" class="start-btn" onclick="start_game_fwc()">开始</button>
            </div>
        </div>
    </div>
{% endblock %}

{% block page-js %}
    <script>
        function getCookie(name) {
            var cookieName = name + "=";
            var decodedCookie = decodeURIComponent(document.cookie);
            var cookieArray = decodedCookie.split(';');
            for (var i = 0; i < cookieArray.length; i++) {
                var cookie = cookieArray[i].trim();
                if (cookie.indexOf(cookieName) === 0) {
                    return cookie.substring(cookieName.length, cookie.length);
                }
            }
            return null;
        }

        var timerInterval; // Variable to store the timer interval
        var timeLeft = 180; // Initial time

        function start_game_fwc() {
            var d = document.getElementById("video-feed");
            d.src = "http://127.0.0.1:8000/fwc_video";
            timeLeft = 180; // Reset the timer
            updateCounterAndTime(); // Update counter and time immediately
            timerInterval = setInterval(updateCounterAndTime, 1000); // Update every second
            console.log("执行到这里");
        }

        function updateCounterAndTime() {
            updateCounter(); // Update the counter (assuming updateCounter is defined)
            var timerElement = document.getElementById("timer");
            timeLeft -= 1; // Decrement time
            timerElement.innerText = timeLeft; // Update the timer element

            if (timeLeft <= 0) {
                clearInterval(timerInterval); // Stop the timer when time is up
                var c = document.getElementById("video-feed");
                c.src = "{% static 'image/gameoverpic.png' %}"
                {#在这里实现将更新score#}
                // 发起 Ajax 请求
                var xhr = new XMLHttpRequest();  // 创建 XMLHttpRequest 对象
                xhr.open("POST", "/update-fwc-score/", true);  // 发送 POST 请求到 /update-score/
                // 添加 CSRF 令牌到请求头
                var csrftoken = getCookie('csrftoken');  // 获取 CSRF 令牌
                xhr.setRequestHeader("X-CSRFToken", csrftoken);  // 将 CSRF 令牌设置为请求头的 X-CSRFToken 字段
                xhr.setRequestHeader("Content-type", "application/json");  // 设置请求头为 JSON 格式
                xhr.onreadystatechange = function () {
                    if (xhr.readyState === 4 && xhr.status === 200) {
                        console.log("Score updated successfully!");  // 打印请求成功的消息到控制台
                    } else {
                        console.log("error!");  // 打印请求成功的消息到控制台
                    }
                };
                fetch('/get_counter_data/')
                    .then(response => response.json())
                    .then(data => {
                        var data1 = {
                            newScore: data.counter  // 要更新的新分数
                        };
                        xhr.send(JSON.stringify(data1));  // 发送包含用户名和新分数的 JSON 数
                    })
                    .catch(error => console.error('Error:', error));


            }
        }

        function updateCounter() {
            // Your existing updateCounter function logic here
            fetch('/get_counter_data/')
                .then(response => response.json())
                .then(data => {
                    document.getElementById('counter').innerText = data.counter;
                })
                .catch(error => console.error('Error:', error));
        }

        // Additional functions or code related to your existing script

        setInterval(updateCounter, 200);


    </script>
{% endblock %}

app01/templates/home.html
{% extends "index.html" %}
{% load static %}

{% block content %}
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/parallax/3.1.0/parallax.min.js"></script>

    <div>
        <div class="swiper">
            <div class="swiper-wrapper">
                <div class="swiper-slide slide01">
                    <div class="slideContent">
                        <div class="slideInfo">
                            <h1>Fruit Slice Challenge!</h1>
                            <br>
                            <br>
                            <br>
                            <br>
                            <p>Welcome to Fruit Slice Challenge!
                                Be careful to avoid the bombs!<br> Earn points for each successful slice and aim for the
                                high score. <br> Get ready to embark on a juicy adventure!
                            </p>

                        </div>

                    </div>
                </div>

            </div>
        </div>


        <a href="/game" class="btn">START<span><i></i></span></a>

        <div>


            <div class="juice">
                <img src="{% static 'image/sc.png' %}" alt="">

            </div>

            <div class="leaves">
                <ul id="scene">
                    <li class="layer" data-depth="-.1">
                        <img src="{% static 'image/leaf01.png' %}" alt="">
                    </li>
                    <li class="layer" data-depth="-.3">
                        <img src="{% static 'image/leaf02.png' %}" alt="">
                    </li>
                    <li class="layer" data-depth="-1.5">
                        <img src="{% static 'image/leaf03.png' %}" alt="">
                    </li>
                    <li class="layer" data-depth=".1">
                        <img src="{% static 'image/leaf04.png' %}" alt="">
                    </li>
                    <li class="layer" data-depth=".3">
                        <img src="{% static 'image/leaf05.png' %}" alt="">
                    </li>
                </ul>
            </div>


        </div>
    </div>

    <script>
        var scene = document.getElementById('scene');
        var parallax = new Parallax(scene);

        TweenMax.from(".logo", 1, {
            opacity: 0,
            x: -20,
            ease: Expo.easeInOut
        })

        {#TweenMax.staggerFrom(".menu-links ul li", 1, {#}
        {#    opacity: 0,#}
        {#    x: -20,#}
        {#    ease: Power3.easeInOut#}
        //}, 0.08)

        TweenMax.from(".search", 1, {
            delay: .5,
            opacity: 0,
            x: -20,
            ease: Expo.easeInOut
        })

        TweenMax.from(".account", 1, {
            delay: .6,
            opacity: 0,
            x: -20,
            ease: Expo.easeInOut
        })

        {#TweenMax.from(".cart", 1, {#}
        {#    delay: .7,#}
        {#    opacity: 0,#}
        {#    x: -20,#}
        {#    ease: Expo.easeInOut#}
        //})

        TweenMax.from(".juice", 1, {
            delay: 2,
            opacity: 0,
            y: -1000,
            ease: Expo.easeInOut
        })

        TweenMax.from(".leaves .layer:nth-child(1)", 2, {
            delay: 2,
            opacity: 0,
            y: -800,
            ease: Expo.easeInOut
        })

        TweenMax.from(".leaves .layer:nth-child(2)", 2, {
            delay: 2.1,
            opacity: 0,
            y: -800,
            ease: Expo.easeInOut
        })

        TweenMax.from(".leaves .layer:nth-child(3)", 2, {
            delay: 2.2,
            opacity: 0,
            y: -800,
            ease: Expo.easeInOut
        })

        TweenMax.from(".leaves .layer:nth-child(4)", 2, {
            delay: 2.3,
            opacity: 0,
            y: -800,
            ease: Expo.easeInOut
        })

        TweenMax.from(".leaves .layer:nth-child(5)", 2, {
            delay: 2.5,
            opacity: 0,
            y: -800,
            ease: Expo.easeInOut
        })

        TweenMax.from(".title", 1, {
            delay: 1,
            opacity: 0,
            y: 20,
            ease: Expo.easeInOut
        })

        TweenMax.from(".tagline", 1, {
            delay: 1.3,
            opacity: 0,
            y: 20,
            ease: Expo.easeInOut
        })

        TweenMax.from(".pages", 1, {
            delay: 1.3,
            opacity: 0,
            y: 20,
            ease: Expo.easeInOut
        })

        TweenMax.from(".more", 1, {
            delay: 1.4,
            opacity: 0,
            y: 20,
            ease: Expo.easeInOut
        })

        TweenMax.from(".desc", 1, {
            delay: 1.4,
            opacity: 0,
            y: 20,
            ease: Expo.easeInOut
        })

        TweenMax.from(".arrows", 1, {
            delay: 2,
            opacity: 0,
            ease: Expo.easeInOut
        })

    </script>

{% endblock %}

app01/templates/home_fwc.html
{% extends "index.html" %}
{% load static %}

{% block content %}
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/parallax/3.1.0/parallax.min.js"></script>

    <div>
        <div class="swiper">
            <div class="swiper-wrapper">
                <div class="swiper-slide slide01">
                    <div class="slideContent">
                        <div class="slideInfo">
                            <h1>Push-up Challenge!</h1>
                            <br>
                            <br>
                            <br>
                            <br>
                            <p>
                                Do your best and surpass yourself!
                            </p>

                        </div>

                    </div>
                </div>

            </div>
        </div>


        <a href="/fwc" class="btn">START<span><i></i></span></a>

        <div>


            <div class="juice">
                <img src="{% static 'image/fwc.png' %}" alt="">
            </div>
            <div style="position: absolute; bottom: 300px; right: 500px;">
                <img src="{% static 'image/dumbbell1.png' %}" alt="" style="width: 200px; height: 200px;">
            </div>
        </div>
    </div>

    <script>
        var scene = document.getElementById('scene');
        var parallax = new Parallax(scene);

        TweenMax.from(".logo", 1, {
            opacity: 0,
            x: -20,
            ease: Expo.easeInOut
        })

        {#TweenMax.staggerFrom(".menu-links ul li", 1, {#}
        {#    opacity: 0,#}
        {#    x: -20,#}
        {#    ease: Power3.easeInOut#}
        //}, 0.08)

        TweenMax.from(".search", 1, {
            delay: .5,
            opacity: 0,
            x: -20,
            ease: Expo.easeInOut
        })

        TweenMax.from(".account", 1, {
            delay: .6,
            opacity: 0,
            x: -20,
            ease: Expo.easeInOut
        })

        {#TweenMax.from(".cart", 1, {#}
        {#    delay: .7,#}
        {#    opacity: 0,#}
        {#    x: -20,#}
        {#    ease: Expo.easeInOut#}
        //})

        TweenMax.from(".juice", 1, {
            delay: 2,
            opacity: 0,
            y: -1000,
            ease: Expo.easeInOut
        })

        TweenMax.from(".leaves .layer:nth-child(1)", 2, {
            delay: 2,
            opacity: 0,
            y: -800,
            ease: Expo.easeInOut
        })

        TweenMax.from(".leaves .layer:nth-child(2)", 2, {
            delay: 2.1,
            opacity: 0,
            y: -800,
            ease: Expo.easeInOut
        })

        TweenMax.from(".leaves .layer:nth-child(3)", 2, {
            delay: 2.2,
            opacity: 0,
            y: -800,
            ease: Expo.easeInOut
        })

        TweenMax.from(".leaves .layer:nth-child(4)", 2, {
            delay: 2.3,
            opacity: 0,
            y: -800,
            ease: Expo.easeInOut
        })

        TweenMax.from(".leaves .layer:nth-child(5)", 2, {
            delay: 2.5,
            opacity: 0,
            y: -800,
            ease: Expo.easeInOut
        })

        TweenMax.from(".title", 1, {
            delay: 1,
            opacity: 0,
            y: 20,
            ease: Expo.easeInOut
        })

        TweenMax.from(".tagline", 1, {
            delay: 1.3,
            opacity: 0,
            y: 20,
            ease: Expo.easeInOut
        })

        TweenMax.from(".pages", 1, {
            delay: 1.3,
            opacity: 0,
            y: 20,
            ease: Expo.easeInOut
        })

        TweenMax.from(".more", 1, {
            delay: 1.4,
            opacity: 0,
            y: 20,
            ease: Expo.easeInOut
        })

        TweenMax.from(".desc", 1, {
            delay: 1.4,
            opacity: 0,
            y: 20,
            ease: Expo.easeInOut
        })

        TweenMax.from(".arrows", 1, {
            delay: 2,
            opacity: 0,
            ease: Expo.easeInOut
        })

    </script>

{% endblock %}

app01/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登录</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
    <style>
        .error-msg {
            color: red;
            position: absolute;
            font-size: 13px;
        }
    </style>
</head>
<body>

{% block content %}
    <div class="box">
        <div class="content">
            <div class="login-wrapper">
                <h1>登录</h1>
                <form method="post" novalidate>
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="exampleInputEmail1" class="form-label">用户名</label>
                        {{ form.username }}
                    </div>
                    <div class="mb-3">
                        <label for="exampleInputPassword1" class="form-label">密码</label>
                        {{ form.password }}
                        <span class="error-msg">{{ form.errors.username.0 }}</span>
                    </div>
                    <div class="mb-3">
                        <label for="id_code" class="form-label">图片验证码</label>
                        <div style="display: flex; align-items: center;">
                            {{ form.code }}
                            <img src="/image/code/" alt="" id="image_code" style="margin-left: 20px;   width: 200px; border: 2px solid black; border-radius: 4px;"
                                 onclick="this.setAttribute('src','/image/code/?random='+Math.random())">
                        </div>
                        <span class="error-msg">{{ form.errors.code.0 }}</span>
                    </div>
                    <div style="text-align: center;">
                        <a style="text-decoration: none;" href="{% url 'signup' %}">没有账号？注册一个</a>
                    </div>
                    <div>
                        <button type="submit" class="button" style="margin-left: 145px">
                            <span>登录</span>
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}


<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>